# Generated by Django 4.0.6 on 2022-09-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_remove_books_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
